name: NPM Publish

on:
  workflow_dispatch:

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  publish:
    # prevents this action from running on forks
    if: github.repository == 'jbukuts/git-cms'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set-up Node
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Transpile
        run: npm run build

      - name: Publish package
        run: npm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
